services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api_c
    hostname: api
    command: npm run start:dev
    env_file:
      - ./api/.env
    depends_on:
      - database
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'

  database:
    image: postgres:14-alpine
    container_name: db_c
    hostname: db
    env_file:
      - ./api/.env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgresql
      - POSTGRES_DB=dbpdt
      #       - POSTGRES_USER=${POSTGRES_USER}
      # - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      # - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
